from setuptools import setup

setup(name='MARM',
      version='2.0',
      description='Melanoma Adaptive Resistance Model',
      author='',
      packages=['MARM'],
      install_requires=[
            'numpy',
            'petab',
            'amici',
            'pypesto==0.2.10',
            'fides==0.7.5',
            'astropy',
            'mizani',
            'plotnine',
            'pandas',
            'matplotlib',
            'seaborn',
            'xlrd',
            'snakemake',
            'tabulate',
            'sklearn',
            'pysb@git+https://github.com/FFroehlich/pysb@energy_modeling',
            'scipy',
            'networkx',
            'jupyter',
            'cite2c'
      ],
      python_requires='>=3.7',
      zip_safe=False)
