# exported from PySB model 'RTKERK__pRAF'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, EnergyPattern, MultiState, Tag, ANY, WILD
from sympy import exp, log

Model()

Monomer('RAFi', ['raf'])
Monomer('PRAFi', ['raf'])
Monomer('MEKi', ['mek'])
Monomer('EGF', ['rtk'])
Monomer('EGFR', ['KD', 'Tyr', 'rtkf', 'ub'], {'Tyr': ['p', 'u'], 'ub': ['false', 'true']})
Monomer('GRB2', ['SH2', 'SH3'])
Monomer('SOS1', ['S1134', 'SH3m', 'ras'], {'S1134': ['p', 'u']})
Monomer('RAS', ['raf', 'sos1', 'state'], {'state': ['gdp', 'gtp']})
Monomer('CBL', ['SH3m'])
Monomer('BRAF', ['AA600', 'RBD', 'mek', 'raf', 'rafi', 'T753'], {'AA600': ['E'], 'T753': ['u', 'p']})
Monomer('CRAF', ['RBD', 'mek', 'raf', 'rafi', 'S642'], {'S642': ['u', 'p']})
Monomer('MEK', ['Dsite', 'meki', 'phospho', 'raf'], {'phospho': ['p', 'u']})
Monomer('ERK', ['CD', 'phospho'], {'phospho': ['p', 'u']})
Monomer('DUSP', ['erk'])
Monomer('mDUSP')
Monomer('mEGFR')
Monomer('SPRY', ['SH3m'])
Monomer('mSPRY')

Parameter('N_Avogadro', 6.02214076e+23)
Parameter('volume', 1e-12)
Parameter('m_Da_EGF', 6200.0)
Parameter('RAFi_0', 0.0)
Parameter('PRAFi_0', 0.0)
Parameter('MEKi_0', 0.0)
Parameter('EGF_0', 0.0)
Parameter('bind_EGF_EGFR_kf', 5414688.356949159)
Parameter('bind_EGF_EGFR_dG', -6.872498769188235, nonnegative=False)
Parameter('bind_EGF_EGFR_phi', 1.0)
Parameter('bind_EGFR_EGFR_kf', 1101950.5763700148)
Parameter('bind_EGFR_EGFR_dG', -7.985149326388008, nonnegative=False)
Parameter('bind_EGFR_EGFR_phi', 1.0)
Parameter('ep_EGFR_EGFR_mod_EGF_single_ddG', -9.907466030766514, nonnegative=False)
Parameter('catalyze_EGFR_EGFR_p_kcat', 13302.67285275614)
Parameter('catalyze_EGFR_u_kcatr', 0.0634037705459066)
Parameter('bind_pEGFR_GRB2_kf', 213864.5147442635)
Parameter('bind_pEGFR_GRB2_dG', -3.610789886662507, nonnegative=False)
Parameter('bind_pEGFR_GRB2_phi', 1.0)
Parameter('bind_CBL_GRB2_kf', 8209151.973566609)
Parameter('bind_CBL_GRB2_dG', -3.034506237375752, nonnegative=False)
Parameter('bind_CBL_GRB2_phi', 1.0)
Parameter('catalyze_CBL_EGFR_ub_kcat', 41752.179694265535)
Parameter('catalyze_EGFR_dub_kcatr', 0.0001041943803855)
Parameter('catalyze_EGFR_endo_kcat', 29095.721295165626)
Parameter('catalyze_EGFR_deg_kM', 0.0025466915128859)
Parameter('catalyze_EGFR_recycl_kcat', 11.616564113097356)
Parameter('catalyze_EGFR_deg_kcat', 74.42145017476678)
Parameter('bind_GRB2_SOS1_kf', 1230352.7211713195)
Parameter('bind_GRB2_SOS1_dG', -9.150014422510427, nonnegative=False)
Parameter('bind_GRB2_SOS1_phi', 1.0)
Parameter('bind_SOS1_RAS_kf', 1212949.6481994835)
Parameter('bind_SOS1_RAS_dG', -5.459201781305085, nonnegative=False)
Parameter('catalyze_SOS1_RAS_gtp_kcat', 9989.653166478583)
Parameter('catalyze_NF1_RAS_gdp_kcatr', 0.0123823703358812)
Parameter('bind_RAF_RAF_kf', 8520.344903742554)
Parameter('bind_RAF_RAF_dG', 2.2207387049661573, nonnegative=False)
Parameter('bind_RAF_RAF_phi', 1.0)
Parameter('bind_RASgtp_RAF_kf', 2506439.8648864483)
Parameter('bind_RASgtp_RAF_dG', -6.155709490340769, nonnegative=False)
Parameter('bind_RASgtp_RAF_phi', 1.0)
Parameter('ep_RAF_RAF_mod_RASgtp_double_ddG', -22.892349744616908, nonnegative=False)
Parameter('bind_RAFi_RAF_kf', 0.0)
Parameter('bind_RAFi_RAF_dG', 0.0, nonnegative=False)
Parameter('bind_RAFi_RAF_phi', 1.0)
Parameter('bind_PRAFi_RAF_kf', 0.0)
Parameter('bind_PRAFi_RAF_dG', 0.0, nonnegative=False)
Parameter('bind_PRAFi_RAF_phi', 1.0)
Parameter('ep_RAF_RAF_mod_RAFi_single_ddG', 0.0, nonnegative=False)
Parameter('ep_RAF_RAF_mod_RAFi_double_ddG', 0.0, nonnegative=False)
Parameter('catalyze_pERK_CRAF_pS642_kcat', 10.074156966753849)
Parameter('catalyze_pERK_BRAF_pT753_kcat', 110.6618581981719)
Parameter('catalyze_phosphatase_CRAF_uS642_kcatr', 0.0039041789957742)
Parameter('catalyze_phosphatase_BRAF_uT753_kcatr', 0.0003454679065461)
Parameter('ep_RAF_RAS_mod_pRAF_ddG', 2.52171598574827, nonnegative=False)
Parameter('ep_RAF_RAF_mod_pRAF_ddG', 4.096747591764383, nonnegative=False)
Parameter('bind_RAF_uMEK_kf', 376.8529664827641)
Parameter('bind_RAF_uMEK_dG', -5.409245380045553, nonnegative=False)
Parameter('bind_RAF_uMEK_phi', 1.0)
Parameter('catalyze_RAF_RAFrafiNone_MEK_p_kcat', 425.8157178974839)
Parameter('catalyze_RAFrafiNone_MEKmekiNone_p_kcat', 10218.511369557677)
Parameter('catalyze_RAFrafiNone_MEKmeki_MEKi_p_kcatr', 0.0)
Parameter('catalyze_PP2A_MEK_u_kcatr', 0.0637813651225339)
Parameter('bind_MEKi_MEK_kf', 0.0)
Parameter('bind_MEKi_MEK_dG', 0.0, nonnegative=False)
Parameter('bind_MEKi_MEK_phi', 1.0)
Parameter('ep_pMEK_MEKi_ddG', 0.0, nonnegative=False)
Parameter('bind_MEK_uERK_kf', 3255988.5022486574)
Parameter('bind_MEK_uERK_dG', -10.857750917505548, nonnegative=False)
Parameter('bind_MEK_uERK_phi', 1.0)
Parameter('catalyze_MEKmekiNone_phosphop_ERK_p_kcat', 8215.273692157907)
Parameter('mSPRY_eq', 10.439984880360536)
Parameter('SPRY_eq', 8814.242376615666)
Parameter('synthesize_pERK_SPRY_ERK_gexpslope', 14226.282480161306)
Parameter('msynthesize_pERK_SPRY_kdeg', 1.5379388868970758)
Parameter('psynthesize_pERK_SPRY_kdeg', 0.1238370841872048)
Parameter('synthesize_pERK_SPRY_ERK_kM', 3.047697507614457)
Parameter('bind_SPRY_GRB2_kf', 247.6683505861666)
Parameter('bind_SPRY_GRB2_dG', -9.075549712041765, nonnegative=False)
Parameter('bind_SPRY_GRB2_phi', 1.0)
Parameter('catalyze_pERK_SOS1_pS1134_kbase', 0.013018061069753)
Parameter('catalyze_pERK_SOS1_pS1134_kcat', 19173.39531841745)
Parameter('catalyze_phosphatase_SOS1_uS1134_kcatr', 0.0425218002551878)
Parameter('ep_SOS1S1134p_GRB2_ddG', 5.766385887220818, nonnegative=False)
Parameter('mEGFR_eq', 12.093663611751916)
Parameter('EGFR_eq', 5644.819774201911)
Parameter('synthesize_pERK_EGFR_ERK_gexpslope', 4.155403115159029)
Parameter('msynthesize_pERK_EGFR_kdeg', 0.2871186170742963)
Parameter('psynthesize_pERK_EGFR_kdeg', 0.2828826114512838)
Parameter('EGFR_crispr', 1.0)
Parameter('synthesize_pERK_EGFR_ERK_kM', 0.0549356044152598)
Parameter('mDUSP_eq', 46.42521654061486)
Parameter('DUSP_eq', 1325.0589075943767)
Parameter('synthesize_pERK_DUSP_ERK_gexpslope', 33.02133961672821)
Parameter('msynthesize_pERK_DUSP_kdeg', 1.4009890808028511)
Parameter('psynthesize_pERK_DUSP_kdeg', 1.2151059494930014)
Parameter('synthesize_pERK_DUSP_ERK_kM', 0.1424494061551368)
Parameter('bind_DUSP_pERK_kf', 2540574.564795284)
Parameter('bind_DUSP_pERK_dG', -12.43927150915225, nonnegative=False)
Parameter('bind_DUSP_pERK_phi', 1.0)
Parameter('catalyze_DUSP_ERK_u_kcatr', 0.1358779619046222)
Parameter('BRAF_0', 1113.3232263775496)
Parameter('CRAF_0', 13313.404710604049)
Parameter('RAS_0', 187523.5447678092)
Parameter('MEK_0', 137259.0329677142)
Parameter('ERK_0', 137606.05124947033)
Parameter('GRB2_0', 49349.94702807723)
Parameter('SOS1_0', 6344.309581440597)
Parameter('CBL_0', 16857.631382306976)
Parameter('pMEK_IF_scale', 34.67019178129089)
Parameter('pMEK_IF_offset', 0.248293083465286)
Parameter('pERK_IF_scale', 1.948775429243194)
Parameter('pERK_IF_offset', 0.0479359691909276)

Expression('initEGF', 6.02214076208112e+23*EGF_0/(N_Avogadro*m_Da_EGF))
Expression('Ea0_bind_EGF_EGFR', -bind_EGF_EGFR_dG*bind_EGF_EGFR_phi - log(bind_EGF_EGFR_kf))
Expression('Ea0_bind_EGFR_EGFR', -bind_EGFR_EGFR_dG*bind_EGFR_EGFR_phi - log(bind_EGFR_EGFR_kf))
Expression('catalyze_EGFR_u_kcat', catalyze_EGFR_EGFR_p_kcat*catalyze_EGFR_u_kcatr)
Expression('Ea0_bind_pEGFR_GRB2', -bind_pEGFR_GRB2_dG*bind_pEGFR_GRB2_phi - log(bind_pEGFR_GRB2_kf))
Expression('Ea0_bind_CBL_GRB2', -bind_CBL_GRB2_dG*bind_CBL_GRB2_phi - log(bind_CBL_GRB2_kf))
Expression('catalyze_EGFR_dub_kcat', catalyze_CBL_EGFR_ub_kcat*catalyze_EGFR_dub_kcatr)
Expression('Ea0_bind_GRB2_SOS1', -bind_GRB2_SOS1_dG*bind_GRB2_SOS1_phi - log(bind_GRB2_SOS1_kf))
Expression('bind_SOS1_RAS_kr', bind_SOS1_RAS_kf*exp(bind_SOS1_RAS_dG))
Expression('catalyze_NF1_RAS_gdp_kcat', catalyze_NF1_RAS_gdp_kcatr*catalyze_SOS1_RAS_gtp_kcat)
Expression('Ea0_bind_RAF_RAF', -bind_RAF_RAF_dG*bind_RAF_RAF_phi - log(bind_RAF_RAF_kf))
Expression('Ea0_bind_RASgtp_BRAF', -bind_RASgtp_RAF_dG*bind_RASgtp_RAF_phi - log(bind_RASgtp_RAF_kf))
Expression('Ea0_bind_RASgtp_CRAF', -bind_RASgtp_RAF_dG*bind_RASgtp_RAF_phi - log(bind_RASgtp_RAF_kf))
Expression('Ea0_bind_RAFi_RAF', -bind_RAFi_RAF_dG*bind_RAFi_RAF_phi - log(bind_RAFi_RAF_kf))
Expression('Ea0_bind_PRAFi_RAF', -bind_PRAFi_RAF_dG*bind_PRAFi_RAF_phi - log(bind_PRAFi_RAF_kf))
Expression('ep_RAF_RAF_mod_RAFi_double_Gf', ep_RAF_RAF_mod_RAFi_double_ddG - ep_RAF_RAF_mod_RAFi_single_ddG)
Expression('catalyze_phosphatase_CRAF_uS642_kcat', catalyze_pERK_CRAF_pS642_kcat*catalyze_phosphatase_CRAF_uS642_kcatr)
Expression('catalyze_phosphatase_BRAF_uT753_kcat', catalyze_pERK_BRAF_pT753_kcat*catalyze_phosphatase_BRAF_uT753_kcatr)
Expression('Ea0_bind_BRAF_uMEK', -bind_RAF_uMEK_dG*bind_RAF_uMEK_phi - log(bind_RAF_uMEK_kf))
Expression('Ea0_bind_CRAF_uMEK', -bind_RAF_uMEK_dG*bind_RAF_uMEK_phi - log(bind_RAF_uMEK_kf))
Expression('catalyze_RAFrafiNone_MEKmekiANY_p_kcat', catalyze_RAFrafiNone_MEKmekiNone_p_kcat*catalyze_RAFrafiNone_MEKmeki_MEKi_p_kcatr)
Expression('catalyze_PP2A_MEK_u_kcat', catalyze_PP2A_MEK_u_kcatr*catalyze_RAF_RAFrafiNone_MEK_p_kcat)
Expression('Ea0_bind_MEKi_MEK', -bind_MEKi_MEK_dG*bind_MEKi_MEK_phi - log(bind_MEKi_MEK_kf))
Expression('Ea0_bind_MEK_uERK', -bind_MEK_uERK_dG*bind_MEK_uERK_phi - log(bind_MEK_uERK_kf))
Expression('msynthesize_pERK_SPRY_kbase', mSPRY_eq*psynthesize_pERK_SPRY_kdeg)
Expression('psynthesize_pERK_SPRY_kbase', 1000000.0*SPRY_eq*psynthesize_pERK_SPRY_kdeg/(N_Avogadro*mSPRY_eq*volume))
Expression('psynthesize_pERK_SPRY_ksyn', psynthesize_pERK_SPRY_kbase)
Expression('Ea0_bind_SPRY_GRB2', -bind_SPRY_GRB2_dG*bind_SPRY_GRB2_phi - log(bind_SPRY_GRB2_kf))
Expression('catalyze_phosphatase_SOS1_uS1134_kcat', catalyze_pERK_SOS1_pS1134_kcat*catalyze_phosphatase_SOS1_uS1134_kcatr)
Expression('msynthesize_pERK_EGFR_kbase', mEGFR_eq*psynthesize_pERK_EGFR_kdeg)
Expression('psynthesize_pERK_EGFR_kbase', 1000000.0*EGFR_eq*psynthesize_pERK_EGFR_kdeg/(N_Avogadro*mEGFR_eq*volume))
Expression('psynthesize_pERK_EGFR_ksyn', psynthesize_pERK_EGFR_kbase)
Expression('msynthesize_pERK_DUSP_kbase', mDUSP_eq*psynthesize_pERK_DUSP_kdeg)
Expression('psynthesize_pERK_DUSP_kbase', 1000000.0*DUSP_eq*psynthesize_pERK_DUSP_kdeg/(N_Avogadro*mDUSP_eq*volume))
Expression('psynthesize_pERK_DUSP_ksyn', psynthesize_pERK_DUSP_kbase)
Expression('Ea0_bind_DUSP_pERK', -bind_DUSP_pERK_dG*bind_DUSP_pERK_phi - log(bind_DUSP_pERK_kf))
Expression('catalyze_DUSP_ERK_u_kcat', catalyze_DUSP_ERK_u_kcatr*catalyze_MEKmekiNone_phosphop_ERK_p_kcat)
Expression('initBRAF', 1000000.0*BRAF_0/(N_Avogadro*volume))
Expression('initCRAF', 1000000.0*CRAF_0/(N_Avogadro*volume))
Expression('initRAS', 1000000.0*RAS_0/(N_Avogadro*volume))
Expression('initMEK', 1000000.0*MEK_0/(N_Avogadro*volume))
Expression('initERK', 1000000.0*ERK_0/(N_Avogadro*volume))
Expression('initGRB2', 1000000.0*GRB2_0/(N_Avogadro*volume))
Expression('initSOS1', 1000000.0*SOS1_0/(N_Avogadro*volume))
Expression('initCBL', 1000000.0*CBL_0/(N_Avogadro*volume))

Compartment(name='EC', parent=None, dimension=3, size=None)
Compartment(name='PM', parent=EC, dimension=2, size=None)
Compartment(name='CP', parent=PM, dimension=3, size=None)
Compartment(name='EM', parent=CP, dimension=2, size=None)

Observable('pEGFR_PM', EGFR(Tyr='p') ** PM)
Observable('modulation_synthesize_pERK_SPRY_ERK', ERK(phospho='p'))
Observable('modulation_synthesize_pERK_EGFR_ERK', ERK(phospho='p'))
Observable('modulation_synthesize_pERK_DUSP_ERK', ERK(phospho='p'))
Observable('tBRAF', BRAF())
Observable('tCRAF', CRAF())
Observable('tRAS', RAS())
Observable('tMEK', MEK())
Observable('tERK', ERK())
Observable('tDUSP', DUSP())
Observable('tEGFR', EGFR())
Observable('tGRB2', GRB2())
Observable('tSPRY', SPRY())
Observable('tSOS1', SOS1())
Observable('tCBL', CBL())
Observable('pERK', ERK(phospho='p'))
Observable('pS1134SOS1', SOS1(S1134='p'))
Observable('tmDUSP', mDUSP())
Observable('tmEGFR', mEGFR())
Observable('tmSPRY', mSPRY())
Observable('pMEK', MEK(phospho='p'))

Expression('catalyze_EGFR_kendo', catalyze_EGFR_endo_kcat/(pEGFR_PM + catalyze_EGFR_deg_kM))
Expression('synthesize_pERK_SPRY_ERK_kmod', modulation_synthesize_pERK_SPRY_ERK*synthesize_pERK_SPRY_ERK_gexpslope/(modulation_synthesize_pERK_SPRY_ERK + synthesize_pERK_SPRY_ERK_kM) + 1)
Expression('msynthesize_pERK_SPRY_ksyn', 1.0*msynthesize_pERK_SPRY_kbase*synthesize_pERK_SPRY_ERK_kmod)
Expression('synthesize_pERK_EGFR_ERK_kmod', modulation_synthesize_pERK_EGFR_ERK*synthesize_pERK_EGFR_ERK_gexpslope/(modulation_synthesize_pERK_EGFR_ERK + synthesize_pERK_EGFR_ERK_kM) + 1)
Expression('msynthesize_pERK_EGFR_ksyn', msynthesize_pERK_EGFR_kbase*synthesize_pERK_EGFR_ERK_kmod*EGFR_crispr)
Expression('synthesize_pERK_DUSP_ERK_kmod', modulation_synthesize_pERK_DUSP_ERK*synthesize_pERK_DUSP_ERK_gexpslope/(modulation_synthesize_pERK_DUSP_ERK + synthesize_pERK_DUSP_ERK_kM) + 1)
Expression('msynthesize_pERK_DUSP_ksyn', 1.0*msynthesize_pERK_DUSP_kbase*synthesize_pERK_DUSP_ERK_kmod)
Expression('tBRAF_obs', log(1.0e-6*tBRAF*N_Avogadro*volume))
Expression('tCRAF_obs', log(1.0e-6*tCRAF*N_Avogadro*volume))
Expression('tRAS_obs', log(1.0e-6*tRAS*N_Avogadro*volume))
Expression('tMEK_obs', log(1.0e-6*tMEK*N_Avogadro*volume))
Expression('tERK_obs', log(1.0e-6*tERK*N_Avogadro*volume))
Expression('tDUSP_obs', log(1.0e-6*tDUSP*N_Avogadro*volume))
Expression('tEGFR_obs', log(1.0e-6*tEGFR*N_Avogadro*volume))
Expression('tGRB2_obs', log(1.0e-6*tGRB2*N_Avogadro*volume))
Expression('tSPRY_obs', log(1.0e-6*tSPRY*N_Avogadro*volume))
Expression('tSOS1_obs', log(1.0e-6*tSOS1*N_Avogadro*volume))
Expression('tCBL_obs', log(1.0e-6*tCBL*N_Avogadro*volume))
Expression('pERK_obs', pERK/tERK)
Expression('pS1134SOS1_obs', pS1134SOS1/tSOS1)
Expression('tmDUSP_obs', log(tmDUSP))
Expression('tmEGFR_obs', log(tmEGFR))
Expression('tmSPRY_obs', log(tmSPRY))
Expression('pMEK_obs', pMEK/tMEK)
Expression('pERK_IF_obs', pERK_obs*pERK_IF_scale + pERK_IF_offset)
Expression('pMEK_IF_obs', pMEK_obs*pMEK_IF_scale + pMEK_IF_offset)

Rule('EGF_and_EGFR_bind_and_dissociate', EGF(rtk=None) + EGFR(rtkf=None) | EGF(rtk=1) % EGFR(rtkf=1), bind_EGF_EGFR_phi, Ea0_bind_EGF_EGFR, energy=True)
Rule('bind_EGFR_EGFRu', EGFR(KD=None, Tyr='u') + EGFR(KD=None, Tyr='u') | EGFR(KD=1, Tyr='u') % EGFR(KD=None, Tyr=('u', 1)), bind_EGFR_EGFR_phi, Ea0_bind_EGFR_EGFR, energy=True)
Rule('bind_EGFR_EGFRp', EGFR(KD=None, Tyr='p') + EGFR(KD=None, Tyr='u') | EGFR(KD=1, Tyr='p') % EGFR(KD=None, Tyr=('u', 1)), bind_EGFR_EGFR_phi, Ea0_bind_EGFR_EGFR, energy=True)
Rule('catalyze_EGFR_EGFR_p', EGFR(KD=1, rtkf=ANY) % EGFR(Tyr=('u', 1)) >> EGFR(KD=None, rtkf=ANY) + EGFR(Tyr='p'), catalyze_EGFR_EGFR_p_kcat)
Rule('catalyze_EGFR_u', EGFR(Tyr='p') >> EGFR(Tyr='u'), catalyze_EGFR_u_kcat)
Rule('bind_pEGFR_GRB2', GRB2(SH2=None) + EGFR(Tyr='p') | GRB2(SH2=1) % EGFR(Tyr=('p', 1)), bind_pEGFR_GRB2_phi, Ea0_bind_pEGFR_GRB2, energy=True)
Rule('CBL_and_GRB2_bind_and_dissociate', CBL(SH3m=None) + GRB2(SH3=None) | CBL(SH3m=1) % GRB2(SH3=1), bind_CBL_GRB2_phi, Ea0_bind_CBL_GRB2, energy=True)
Rule('catalyze_CBL_EGFR_ub', EGFR(ub='false') % CBL() >> EGFR(ub='true') % CBL(), catalyze_CBL_EGFR_ub_kcat)
Rule('catalyze_EGFR_dub', EGFR(ub='true') >> EGFR(ub='false'), catalyze_EGFR_dub_kcat)
Rule('pEGFR_is_endocytosed', EGFR(Tyr='p') ** PM >> EGFR(Tyr='p') ** EM, catalyze_EGFR_kendo, move_connected=True)
Rule('EGFR_is_recycled', EGFR() ** EM >> EGFR() ** PM, catalyze_EGFR_recycl_kcat, move_connected=True)
Rule('ubEGFR_is_degraded', EGFR(ub='true') ** EM >> None, catalyze_EGFR_deg_kcat, delete_molecules=True)
Rule('GRB2_and_SOS1_bind_and_dissociate', GRB2(SH3=None) + SOS1(SH3m=None) | GRB2(SH3=1) % SOS1(SH3m=1), bind_GRB2_SOS1_phi, Ea0_bind_GRB2_SOS1, energy=True)
Rule('RTK_and_GRB2_bound_SOS1_binds_RASgdp', GRB2(SH2=ANY, SH3=1) % SOS1(SH3m=1, ras=None) + RAS(sos1=None, state='gdp') >> GRB2(SH2=ANY, SH3=1) % SOS1(SH3m=1, ras=2) % RAS(sos1=2, state='gdp'), bind_SOS1_RAS_kf)
Rule('SOS1_dissociates_from_RAS', SOS1(ras=1) % RAS(sos1=1) >> SOS1(ras=None) + RAS(sos1=None), bind_SOS1_RAS_kr)
Rule('SOS1_catalyzes_RAS_guanosine_exchange', SOS1(ras=1) % RAS(sos1=1, state='gdp') >> SOS1(ras=None) + RAS(sos1=None, state='gtp'), catalyze_SOS1_RAS_gtp_kcat)
Rule('RAS_hydrolysis_GTP', RAS(raf=None, state='gtp') >> RAS(raf=None, state='gdp'), catalyze_NF1_RAS_gdp_kcat)
Rule('BRAF_and_BRAF_bind_and_dissociate', BRAF(raf=None) + BRAF(raf=None) | BRAF(raf=1) % BRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_RAF_RAF, energy=True)
Rule('BRAF_and_CRAF_bind_and_dissociate', BRAF(raf=None) + CRAF(raf=None) | BRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_RAF_RAF, energy=True)
Rule('CRAF_and_CRAF_bind_and_dissociate', CRAF(raf=None) + CRAF(raf=None) | CRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_phi, Ea0_bind_RAF_RAF, energy=True)
Rule('RASgtp_and_BRAF_bind_and_dissociate', RAS(raf=None, state='gtp') + BRAF(RBD=None) | RAS(raf=1, state='gtp') % BRAF(RBD=1), bind_RASgtp_RAF_phi, Ea0_bind_RASgtp_BRAF, energy=True)
Rule('RASgtp_and_CRAF_bind_and_dissociate', RAS(raf=None, state='gtp') + CRAF(RBD=None) | RAS(raf=1, state='gtp') % CRAF(RBD=1), bind_RASgtp_RAF_phi, Ea0_bind_RASgtp_CRAF, energy=True)
Rule('GTP_hydrolysis_dissociates_BRAF_from_RAS', RAS(raf=1, state='gtp') % BRAF(RBD=1) >> RAS(raf=None, state='gdp') + BRAF(RBD=None), catalyze_NF1_RAS_gdp_kcat)
Rule('GTP_hydrolysis_dissociates_CRAF_from_RAS', RAS(raf=1, state='gtp') % CRAF(RBD=1) >> RAS(raf=None, state='gdp') + CRAF(RBD=None), catalyze_NF1_RAS_gdp_kcat)
Rule('RAFi_and_BRAF_bind_and_dissociate', RAFi(raf=None) + BRAF(rafi=None) | RAFi(raf=1) % BRAF(rafi=1), bind_RAFi_RAF_phi, Ea0_bind_RAFi_RAF, energy=True)
Rule('RAFi_and_CRAF_bind_and_dissociate', RAFi(raf=None) + CRAF(rafi=None) | RAFi(raf=1) % CRAF(rafi=1), bind_RAFi_RAF_phi, Ea0_bind_RAFi_RAF, energy=True)
Rule('PRAFi_and_BRAF_bind_and_dissociate', PRAFi(raf=None) + BRAF(rafi=None) | PRAFi(raf=1) % BRAF(rafi=1), bind_PRAFi_RAF_phi, Ea0_bind_PRAFi_RAF, energy=True)
Rule('PRAFi_and_CRAF_bind_and_dissociate', PRAFi(raf=None) + CRAF(rafi=None) | PRAFi(raf=1) % CRAF(rafi=1), bind_PRAFi_RAF_phi, Ea0_bind_PRAFi_RAF, energy=True)
Rule('pERK_phosphorylates_CRAF', ERK(phospho='p') + CRAF(raf=None, S642='u') >> ERK(phospho='p') + CRAF(raf=None, S642='p'), catalyze_pERK_CRAF_pS642_kcat)
Rule('pERK_phosphorylates_BRAF', ERK(phospho='p') + BRAF(raf=None, T753='u') >> ERK(phospho='p') + BRAF(raf=None, T753='p'), catalyze_pERK_BRAF_pT753_kcat)
Rule('CRAF_is_dephosphorylated', CRAF(raf=None, S642='p') >> CRAF(raf=None, S642='u'), catalyze_phosphatase_CRAF_uS642_kcat)
Rule('BRAF_is_dephosphorylated', BRAF(raf=None, T753='p') >> BRAF(raf=None, T753='u'), catalyze_phosphatase_BRAF_uT753_kcat)
Rule('BRAF_and_uMEK_bind_and_dissociate', BRAF(mek=None) + MEK(phospho='u', raf=None) | BRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_uMEK_phi, Ea0_bind_BRAF_uMEK, energy=True)
Rule('CRAF_and_uMEK_bind_and_dissociate', CRAF(mek=None) + MEK(phospho='u', raf=None) | CRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_uMEK_phi, Ea0_bind_CRAF_uMEK, energy=True)
Rule('BRAF_BRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % BRAF(RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + BRAF(RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2), catalyze_RAF_RAFrafiNone_MEK_p_kcat)
Rule('BRAF_CRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % BRAF(RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + BRAF(RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2), catalyze_RAF_RAFrafiNone_MEK_p_kcat)
Rule('CRAF_BRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % CRAF(RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + CRAF(RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=ANY, raf=2), catalyze_RAF_RAFrafiNone_MEK_p_kcat)
Rule('CRAF_CRAF_phosphorylates_MEK', MEK(phospho='u', raf=1) % CRAF(RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2) >> MEK(phospho='p', raf=None) + CRAF(RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=ANY, raf=2), catalyze_RAF_RAFrafiNone_MEK_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_bound1', MEK(meki=ANY, phospho='u', raf=1) % BRAF(AA600='E', mek=1, raf=None, rafi=None) >> MEK(meki=ANY, phospho='p', raf=None) + BRAF(AA600='E', mek=None, raf=None, rafi=None), catalyze_RAFrafiNone_MEKmekiANY_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_bound2', MEK(meki=ANY, phospho='u', raf=1) % BRAF(AA600='E', RBD=None, mek=1, raf=ANY, rafi=None) >> MEK(meki=ANY, phospho='p', raf=None) + BRAF(AA600='E', RBD=None, mek=None, raf=ANY, rafi=None), catalyze_RAFrafiNone_MEKmekiANY_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_bound3', MEK(meki=ANY, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=None, raf=2) >> MEK(meki=ANY, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEKmekiANY_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_bound4', MEK(meki=ANY, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=None, raf=2) >> MEK(meki=ANY, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEKmekiANY_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_unbound1', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', mek=1, raf=None, rafi=None) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', mek=None, raf=None, rafi=None), catalyze_RAFrafiNone_MEKmekiNone_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_unbound2', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=None, mek=1, raf=ANY, rafi=None) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=None, mek=None, raf=ANY, rafi=None), catalyze_RAFrafiNone_MEKmekiNone_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_unbound3', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % BRAF(RBD=None, raf=2) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % BRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEKmekiNone_p_kcat)
Rule('BRAFV600E_phosphorylates_MEK_unbound4', MEK(meki=None, phospho='u', raf=1) % BRAF(AA600='E', RBD=ANY, mek=1, raf=2, rafi=None) % CRAF(RBD=None, raf=2) >> MEK(meki=None, phospho='p', raf=None) + BRAF(AA600='E', RBD=ANY, mek=None, raf=2, rafi=None) % CRAF(RBD=None, raf=2), catalyze_RAFrafiNone_MEKmekiNone_p_kcat)
Rule('MEK_is_dephosphorylated', MEK(phospho='p') >> MEK(phospho='u'), catalyze_PP2A_MEK_u_kcat)
Rule('MEKi_and_MEK_bind_and_dissociate', MEKi(mek=None) + MEK(meki=None) | MEKi(mek=1) % MEK(meki=1), bind_MEKi_MEK_phi, Ea0_bind_MEKi_MEK, energy=True)
Rule('bind_MEK_uERK', MEK(Dsite=None) + ERK(CD=None, phospho='u') | MEK(Dsite=1) % ERK(CD=1, phospho='u'), bind_MEK_uERK_phi, Ea0_bind_MEK_uERK, energy=True)
Rule('pMEK_phosphorylates_ERK', ERK(CD=1, phospho='u') % MEK(Dsite=1, meki=None, phospho='p') >> ERK(CD=None, phospho='p') + MEK(Dsite=None, meki=None, phospho='p'), catalyze_MEKmekiNone_phosphop_ERK_p_kcat)
Rule('synthesis_mSPRY', None >> mSPRY() ** CP, msynthesize_pERK_SPRY_ksyn)
Rule('basal_degradation_mSPRY', mSPRY() >> None, msynthesize_pERK_SPRY_kdeg, delete_molecules=True)
Rule('synthesis_pSPRY', mSPRY() ** CP >> mSPRY() ** CP + SPRY(SH3m=None) ** CP, psynthesize_pERK_SPRY_ksyn)
Rule('basal_degradation_pSPRY', SPRY() >> None, psynthesize_pERK_SPRY_kdeg, delete_molecules=True)
Rule('SPRY_and_GRB2_bind_and_dissociate', SPRY(SH3m=None) + GRB2(SH3=None) | SPRY(SH3m=1) % GRB2(SH3=1), bind_SPRY_GRB2_phi, Ea0_bind_SPRY_GRB2, energy=True)
Rule('SOS1_is_phosphorylated', SOS1(S1134='u') >> SOS1(S1134='p'), catalyze_pERK_SOS1_pS1134_kbase)
Rule('SOS1_is_dephosphorylated', SOS1(S1134='p') >> SOS1(S1134='u'), catalyze_phosphatase_SOS1_uS1134_kcat)
Rule('pERK_phosphorylates_SOS1', ERK(phospho='p') + SOS1(S1134='u') >> ERK(phospho='p') + SOS1(S1134='p'), catalyze_pERK_SOS1_pS1134_kcat)
Rule('synthesis_mEGFR', None >> mEGFR() ** PM, msynthesize_pERK_EGFR_ksyn)
Rule('basal_degradation_mEGFR', mEGFR() >> None, msynthesize_pERK_EGFR_kdeg, delete_molecules=True)
Rule('synthesis_pEGFR', mEGFR() ** PM >> mEGFR() ** PM + EGFR(KD=None, Tyr='u', rtkf=None, ub='false') ** PM, psynthesize_pERK_EGFR_ksyn)
Rule('basal_degradation_pEGFR', EGFR() >> None, psynthesize_pERK_EGFR_kdeg, delete_molecules=True)
Rule('synthesis_mDUSP', None >> mDUSP() ** CP, msynthesize_pERK_DUSP_ksyn)
Rule('basal_degradation_mDUSP', mDUSP() >> None, msynthesize_pERK_DUSP_kdeg, delete_molecules=True)
Rule('synthesis_pDUSP', mDUSP() ** CP >> mDUSP() ** CP + DUSP(erk=None) ** CP, psynthesize_pERK_DUSP_ksyn)
Rule('basal_degradation_pDUSP', DUSP() >> None, psynthesize_pERK_DUSP_kdeg, delete_molecules=True)
Rule('bind_DUSP_pERK', DUSP(erk=None) + ERK(CD=None, phospho='p') | DUSP(erk=1) % ERK(CD=1, phospho='p'), bind_DUSP_pERK_phi, Ea0_bind_DUSP_pERK, energy=True)
Rule('DUSP_dephosphorylates_ERK', ERK(CD=1, phospho='p') % DUSP(erk=1) >> ERK(CD=None, phospho='u') + DUSP(erk=None), catalyze_DUSP_ERK_u_kcat)

EnergyPattern('ep_bind_EGF_EGFR', EGF(rtk=1) % EGFR(rtkf=1), bind_EGF_EGFR_dG)
EnergyPattern('ep_bind_EGFR_EGFR', EGFR(KD=1) % EGFR(Tyr=1), bind_EGFR_EGFR_dG)
EnergyPattern('ep_EGFR_EGFR_EGF', EGF(rtk=1) % EGFR(KD=ANY, rtkf=1), ep_EGFR_EGFR_mod_EGF_single_ddG)
EnergyPattern('ep_bind_pEGFR_GRB2', EGFR(Tyr=1) % GRB2(SH2=1), bind_pEGFR_GRB2_dG)
EnergyPattern('ep_bind_CBL_GRB2', CBL(SH3m=1) % GRB2(SH3=1), bind_CBL_GRB2_dG)
EnergyPattern('ep_bind_GRB2_SOS1', GRB2(SH3=1) % SOS1(SH3m=1), bind_GRB2_SOS1_dG)
EnergyPattern('ep_bind_BRAF_BRAF', BRAF(raf=1) % BRAF(raf=1), bind_RAF_RAF_dG)
EnergyPattern('ep_bind_BRAF_CRAF', BRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_dG)
EnergyPattern('ep_bind_CRAF_CRAF', CRAF(raf=1) % CRAF(raf=1), bind_RAF_RAF_dG)
EnergyPattern('ep_bind_RASgtp_BRAF', RAS(raf=1, state='gtp') % BRAF(RBD=1), bind_RASgtp_RAF_dG)
EnergyPattern('ep_bind_RASgtp_CRAF', RAS(raf=1, state='gtp') % CRAF(RBD=1), bind_RASgtp_RAF_dG)
EnergyPattern('ep_BRAF_BRAF_mod_RAS_double', RAS(raf=2, state='gtp') % BRAF(RBD=2, raf=1) % BRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASgtp_double_ddG)
EnergyPattern('ep_BRAF_CRAF_mod_RAS_double', RAS(raf=2, state='gtp') % BRAF(RBD=2, raf=1) % CRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASgtp_double_ddG)
EnergyPattern('ep_CRAF_CRAF_mod_RAS_double', RAS(raf=2, state='gtp') % CRAF(RBD=2, raf=1) % CRAF(RBD=3, raf=1) % RAS(raf=3, state='gtp'), ep_RAF_RAF_mod_RASgtp_double_ddG)
EnergyPattern('ep_bind_RAFi_BRAF', RAFi(raf=1) % BRAF(rafi=1), bind_RAFi_RAF_dG)
EnergyPattern('ep_bind_RAFi_CRAF', RAFi(raf=1) % CRAF(rafi=1), bind_RAFi_RAF_dG)
EnergyPattern('ep_bind_PRAFi_BRAF', PRAFi(raf=1) % BRAF(rafi=1), bind_PRAFi_RAF_dG)
EnergyPattern('ep_bind_PRAFi_CRAF', PRAFi(raf=1) % CRAF(rafi=1), bind_PRAFi_RAF_dG)
EnergyPattern('ep_BRAF_BRAF_mod_RAFi_single', BRAF(raf=1) % BRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_ddG)
EnergyPattern('ep_BRAF_CRAF_mod_RAFi_single', BRAF(raf=1) % CRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_ddG)
EnergyPattern('ep_CRAF_BRAF_mod_RAFi_single', CRAF(raf=1) % BRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_ddG)
EnergyPattern('ep_CRAF_CRAF_mod_RAFi_single', CRAF(raf=1) % CRAF(raf=1, rafi=2) % RAFi(raf=2), ep_RAF_RAF_mod_RAFi_single_ddG)
EnergyPattern('ep_BRAF_BRAF_mod_RAFi_double', RAFi(raf=2) % BRAF(raf=1, rafi=2) % BRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_BRAF_CRAF_mod_RAFi_double', RAFi(raf=2) % BRAF(raf=1, rafi=2) % CRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_CRAF_CRAF_mod_RAFi_double', RAFi(raf=2) % CRAF(raf=1, rafi=2) % CRAF(raf=1, rafi=3) % RAFi(raf=3), ep_RAF_RAF_mod_RAFi_double_Gf)
EnergyPattern('ep_BRAF_RAF_mod_pRAF', BRAF(raf=ANY, T753='p'), ep_RAF_RAF_mod_pRAF_ddG)
EnergyPattern('ep_CRAF_RAF_mod_pRAF', CRAF(raf=ANY, S642='p'), ep_RAF_RAF_mod_pRAF_ddG)
EnergyPattern('ep_BRAF_RAS_mod_pRAF', BRAF(RBD=ANY, T753='p'), ep_RAF_RAS_mod_pRAF_ddG)
EnergyPattern('ep_CRAF_RAS_mod_pRAF', CRAF(RBD=ANY, S642='p'), ep_RAF_RAS_mod_pRAF_ddG)
EnergyPattern('ep_bind_BRAF_uMEK', BRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_uMEK_dG)
EnergyPattern('ep_bind_CRAF_uMEK', CRAF(mek=1) % MEK(phospho='u', raf=1), bind_RAF_uMEK_dG)
EnergyPattern('ep_bind_MEKi_MEK', MEKi(mek=1) % MEK(meki=1), bind_MEKi_MEK_dG)
EnergyPattern('ep_pMEK_MEKi_single', MEK(meki=1, phospho='p') % MEKi(mek=1), ep_pMEK_MEKi_ddG)
EnergyPattern('ep_bind_MEK_uERK', MEK(Dsite=1) % ERK(CD=1, phospho='u'), bind_MEK_uERK_dG)
EnergyPattern('ep_bind_SPRY_GRB2', SPRY(SH3m=1) % GRB2(SH3=1), bind_SPRY_GRB2_dG)
EnergyPattern('ep_SOS1S1134p_GRB2_single', SOS1(S1134='p', SH3m=1) % GRB2(SH3=1), ep_SOS1S1134p_GRB2_ddG)
EnergyPattern('ep_bind_DUSP_pERK', DUSP(erk=1) % ERK(CD=1, phospho='p'), bind_DUSP_pERK_dG)

Initial(RAFi(raf=None) ** CP, RAFi_0, fixed=True)
Initial(PRAFi(raf=None) ** CP, PRAFi_0, fixed=True)
Initial(MEKi(mek=None) ** CP, MEKi_0, fixed=True)
Initial(EGF(rtk=None) ** CP, initEGF, fixed=True)
Initial(BRAF(AA600='E', RBD=None, mek=None, raf=None, rafi=None, T753='u') ** CP, initBRAF)
Initial(CRAF(RBD=None, mek=None, raf=None, rafi=None, S642='u') ** CP, initCRAF)
Initial(RAS(raf=None, sos1=None, state='gdp') ** CP, initRAS)
Initial(MEK(Dsite=None, meki=None, phospho='u', raf=None) ** CP, initMEK)
Initial(ERK(CD=None, phospho='u') ** CP, initERK)
Initial(GRB2(SH2=None, SH3=None) ** CP, initGRB2)
Initial(SOS1(S1134='u', SH3m=None, ras=None) ** CP, initSOS1)
Initial(CBL(SH3m=None) ** CP, initCBL)

Annotation(RAFi, 'http://identifiers.org/chebi/63637', 'is')
Annotation(PRAFi, 'http://identifiers.org/chebi/167662', 'is')
Annotation(MEKi, 'http://identifiers.org/chebi/90851', 'is')
Annotation(EGF, 'http://identifiers.org/uniprot/P01133', 'is')
Annotation(EGFR, 'http://identifiers.org/uniprot/P00533', 'is')
Annotation(GRB2, 'http://identifiers.org/uniprot/P62993', 'is')
Annotation(SOS1, 'http://identifiers.org/uniprot/Q07889', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01111', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01116', 'is')
Annotation(RAS, 'http://identifiers.org/uniprot/P01112', 'is')
Annotation(CBL, 'http://identifiers.org/uniprot/P22681', 'is')
Annotation(ep_EGFR_EGFR_EGF, 'http://identifiers.org/pubmed/16946702', 'isDescribedBy')
Annotation(ep_EGFR_EGFR_EGF, 'http://identifiers.org/pubmed/16946702', 'isDescribedBy')
Annotation(bind_pEGFR_GRB2, 'http://identifiers.org/pubmed/16777603', 'isDescribedBy')
Annotation(GRB2_and_SOS1_bind_and_dissociate, 'http://identifiers.org/pubmed/7893993', 'isDescribedBy')
Annotation(BRAF, 'http://identifiers.org/uniprot/P15056', 'is')
Annotation(CRAF, 'http://identifiers.org/uniprot/P04049', 'is')
Annotation(MEK, 'http://identifiers.org/uniprot/Q02750', 'is')
Annotation(MEK, 'http://identifiers.org/uniprot/P36507', 'is')
Annotation(ERK, 'http://identifiers.org/uniprot/P27361', 'is')
Annotation(ERK, 'http://identifiers.org/uniprot/P28482', 'is')
Annotation(DUSP, 'http://identifiers.org/uniprot/Q13115', 'is')
Annotation(DUSP, 'http://identifiers.org/uniprot/Q16828', 'is')
Annotation(mDUSP, 'http://identifiers.org/hgnc/3070', 'is')
Annotation(mDUSP, 'http://identifiers.org/hgnc/3072', 'is')
Annotation(mEGFR, 'http://identifiers.org/hgnc/3236', 'is')
Annotation(SPRY, 'http://identifiers.org/uniprot/O43597', 'is')
Annotation(SPRY, 'http://identifiers.org/uniprot/Q9C004', 'is')
Annotation(mSPRY, 'http://identifiers.org/hgnc/11270', 'is')
Annotation(mSPRY, 'http://identifiers.org/hgnc/15533', 'is')

